# Generated by Django 3.2.25 on 2025-04-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20250323_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMGpost', models.ImageField(null=True, upload_to='')),
                ('VIDEOpost', models.FileField(null=True, upload_to='videos/')),
                ('comment', models.CharField(max_length=1000)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
