# Generated by Django 3.2.25 on 2025-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='VIDEOpost',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
